site:
   title: Antora Docs
   start_page: component-b::index.adoc
content:
   sources:
   - url: https://github.com/gargvishu2000/antora_project_2.git
     branches: HEAD
     start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true         